version: '2.1'
services:
    ntp-server:
       image: 180.169.210.141:55788/bfop/ntp:v3
       container_name: ntp-server
       restart: always
       privileged: true
       environment:
         - NTP_CLUSTER_IP_LIST=localhost
         - NTP_NODE_USER=deployer
         - NTP_NODE_PASSWORD=Emotibot1
         - SPECIFY_NTP_SERVER=cn.pool.ntp.org
       volumes:
          - /etc/localtime:/etc/localtime
