
CREATE DATABASE IF NOT EXISTS `emotibot` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `emotibot` ;

CREATE TABLE IF NOT EXISTS `entity_class` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `appid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '机器人id',
  `name` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '类别名称',
  `pid` int(20) DEFAULT NULL COMMENT '父类别名称',
  `editable` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否可编辑',
  `intent_engine` tinyint(1) NOT NULL DEFAULT '1',
  `rule_engine` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `IDX_appid` (`appid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='词库类别';

CREATE TABLE IF NOT EXISTS `entities` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `appid` char(36) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '机器人id',
  `name` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '类别名称',
  `editable` tinyint(1) DEFAULT NULL COMMENT '是否可编辑',
  `cid` int(20) DEFAULT NULL COMMENT '类别id',
  `similar_words` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '同义词',
  `answer` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '敏感词回复',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `IDX_cid` (`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='词库';

INSERT INTO `entity_class` (`appid`, `name`, `pid`, `editable`, `intent_engine`, `rule_engine`, `created_at`) VALUES
('', '任务引擎词库', NULL, 0, 0, 1, CURRENT_TIMESTAMP),
('csbot', '任务引擎词库', NULL, 0, 0, 1, CURRENT_TIMESTAMP),
('templateadmin', '任务引擎词库', NULL, 0, 0, 1, CURRENT_TIMESTAMP);

SET @TERootID = (SELECT e.id FROM `entity_class` e WHERE e.appid = 'templateadmin' and e.name = '任务引擎词库');
INSERT INTO `entity_class` (`appid`, `name`, `pid`, `editable`, `intent_engine`, `rule_engine`, `created_at`) VALUES
('templateadmin', '房型', @TERootID, 0, 0, 1, CURRENT_TIMESTAMP),
('templateadmin', '航空公司代号', @TERootID, 0, 0, 1, CURRENT_TIMESTAMP),
('templateadmin', '城市代号', @TERootID, 0, 0, 1, CURRENT_TIMESTAMP);

SET @RoomTypeID = (SELECT e.id FROM `entity_class` e WHERE e.appid = 'templateadmin' and e.name = '房型');
SET @AirlineID = (SELECT e.id FROM `entity_class` e WHERE e.appid = 'templateadmin' and e.name = '航空公司代号');
SET @CityCodeID = (SELECT e.id FROM `entity_class` e WHERE e.appid = 'templateadmin' and e.name = '城市代号');
INSERT INTO `entities` (`appid`, `name`, `editable`, `cid`, `similar_words`, `answer`, `created_at`)
VALUES
('templateadmin','单人房',0,@RoomTypeID,'single,单人房,单人床,单人房型','',CURRENT_TIMESTAMP),
('templateadmin','双人房',0,@RoomTypeID,'double,双人房,双人床,双人,双人房型,twin','',CURRENT_TIMESTAMP),
('templateadmin','两小床双人房',0,@RoomTypeID,'twin,两小床双人房,双床双人房','',CURRENT_TIMESTAMP),
('templateadmin','三人房',0,@RoomTypeID,'triple,三人房,三人床,三人,三人房型','',CURRENT_TIMESTAMP),
('templateadmin','单床小双人房',0,@RoomTypeID,'semi-double,单床小双人房','',CURRENT_TIMESTAMP),
('templateadmin','套房',0,@RoomTypeID,'suite,套房,套房房型','',CURRENT_TIMESTAMP),
('templateadmin','CA',0,@AirlineID,'中国国际航空公司,中国国航,国航','',CURRENT_TIMESTAMP),
('templateadmin','HU',0,@AirlineID,'海南航空,海航,海南航空公司','',CURRENT_TIMESTAMP),
('templateadmin','JD',0,@AirlineID,'首都航空,北京首都航空有限公司','',CURRENT_TIMESTAMP),
('templateadmin','MU',0,@AirlineID,'东方航空,东航','',CURRENT_TIMESTAMP),
('templateadmin','CZ',0,@AirlineID,'南方航空,南航','',CURRENT_TIMESTAMP),
('templateadmin','BK',0,@AirlineID,'奥凯航空公司,奥凯航空','',CURRENT_TIMESTAMP),
('templateadmin','GJ',0,@AirlineID,'长龙航空公司,长龙航空','',CURRENT_TIMESTAMP),
('templateadmin','9C',0,@AirlineID,'春秋航空公司,春秋航空','',CURRENT_TIMESTAMP),
('templateadmin','EU',0,@AirlineID,'成都航空有限公司,成都航空','',CURRENT_TIMESTAMP),
('templateadmin','CN',0,@AirlineID,'大新华航空公司,新华航空,大新华航空','',CURRENT_TIMESTAMP),
('templateadmin','DZ',0,@AirlineID,'东海航空公司,东海航空','',CURRENT_TIMESTAMP),
('templateadmin','NS',0,@AirlineID,'河北航空公司,河北航空','',CURRENT_TIMESTAMP),
('templateadmin','G5',0,@AirlineID,'华夏航空公司,华夏航空','',CURRENT_TIMESTAMP),
('templateadmin','HO',0,@AirlineID,'吉祥航空公司,吉祥航空','',CURRENT_TIMESTAMP),
('templateadmin','KY',0,@AirlineID,'昆明航空有限公司,昆明航空','',CURRENT_TIMESTAMP),
('templateadmin','QW',0,@AirlineID,'青岛航空公司,青岛航空','',CURRENT_TIMESTAMP),
('templateadmin','3U',0,@AirlineID,'四川航空公司,四川航空,川航','',CURRENT_TIMESTAMP),
('templateadmin','SC',0,@AirlineID,'山东航空公司,山东航空','',CURRENT_TIMESTAMP),
('templateadmin','ZH',0,@AirlineID,'深圳航空公司,深圳航空,深航','',CURRENT_TIMESTAMP),
('templateadmin','FM',0,@AirlineID,'上海航空公司,上海航空,上航','',CURRENT_TIMESTAMP),
('templateadmin','GS',0,@AirlineID,'天津航空有限责任公司,天津航空公司,天津航空,天航','',CURRENT_TIMESTAMP),
('templateadmin','PN',0,@AirlineID,'西部航空公司,西部航空','',CURRENT_TIMESTAMP),
('templateadmin','TV',0,@AirlineID,'西藏航空公司,西藏航空','',CURRENT_TIMESTAMP),
('templateadmin','JR',0,@AirlineID,'幸福航空有限责任公司,幸福航空公司,幸福航空','',CURRENT_TIMESTAMP),
('templateadmin','MF',0,@AirlineID,'厦门航空有限公司,厦门航空公司,厦门航空,厦航','',CURRENT_TIMESTAMP),
('templateadmin','8L',0,@AirlineID,'祥鹏航空公司,祥鹏航空','',CURRENT_TIMESTAMP),
('templateadmin','YI',0,@AirlineID,'英安航空公司,英安航空','',CURRENT_TIMESTAMP),
('templateadmin','KN',0,@AirlineID,'中国联合航空公司,中国联合航空,联航','',CURRENT_TIMESTAMP),
('templateadmin','ZHY',0,@CityCodeID,'中卫','',CURRENT_TIMESTAMP),
('templateadmin','LLB',0,@CityCodeID,'荔波','',CURRENT_TIMESTAMP),
('templateadmin','JZH',0,@CityCodeID,'九寨沟','',CURRENT_TIMESTAMP),
('templateadmin','NBS',0,@CityCodeID,'长白山','',CURRENT_TIMESTAMP),
('templateadmin','ENY',0,@CityCodeID,'延安','',CURRENT_TIMESTAMP),
('templateadmin','JNG',0,@CityCodeID,'济宁','',CURRENT_TIMESTAMP),
('templateadmin','YIC',0,@CityCodeID,'宜春','',CURRENT_TIMESTAMP),
('templateadmin','JUH',0,@CityCodeID,'池州','',CURRENT_TIMESTAMP),
('templateadmin','LIA',0,@CityCodeID,'梁平','',CURRENT_TIMESTAMP),
('templateadmin','RIZ',0,@CityCodeID,'日照','',CURRENT_TIMESTAMP),
('templateadmin','AVA',0,@CityCodeID,'安顺','',CURRENT_TIMESTAMP),
('templateadmin','YIH',0,@CityCodeID,'宜昌','',CURRENT_TIMESTAMP),
('templateadmin','HTN',0,@CityCodeID,'和田','',CURRENT_TIMESTAMP),
('templateadmin','SHASHA',0,@CityCodeID,'上海虹桥','',CURRENT_TIMESTAMP),
('templateadmin','KWE',0,@CityCodeID,'贵阳','',CURRENT_TIMESTAMP),
('templateadmin','KOW',0,@CityCodeID,'赣州','',CURRENT_TIMESTAMP),
('templateadmin','SYX',0,@CityCodeID,'三亚','',CURRENT_TIMESTAMP),
('templateadmin','JNZ',0,@CityCodeID,'锦州','',CURRENT_TIMESTAMP),
('templateadmin','ZAT',0,@CityCodeID,'昭通','',CURRENT_TIMESTAMP),
('templateadmin','XFN',0,@CityCodeID,'襄阳','',CURRENT_TIMESTAMP),
('templateadmin','CGO',0,@CityCodeID,'郑州','',CURRENT_TIMESTAMP),
('templateadmin','HEK',0,@CityCodeID,'黑河','',CURRENT_TIMESTAMP),
('templateadmin','LDS',0,@CityCodeID,'伊春','',CURRENT_TIMESTAMP),
('templateadmin','HZG',0,@CityCodeID,'汉中','',CURRENT_TIMESTAMP),
('templateadmin','HXD',0,@CityCodeID,'德令哈','',CURRENT_TIMESTAMP),
('templateadmin','SYM',0,@CityCodeID,'普洱','',CURRENT_TIMESTAMP),
('templateadmin','TGO',0,@CityCodeID,'通辽','',CURRENT_TIMESTAMP),
('templateadmin','SZX',0,@CityCodeID,'深圳','',CURRENT_TIMESTAMP),
('templateadmin','SHAPVG',0,@CityCodeID,'上海浦东','',CURRENT_TIMESTAMP),
('templateadmin','JDZ',0,@CityCodeID,'景德镇','',CURRENT_TIMESTAMP),
('templateadmin','HYN',0,@CityCodeID,'台州','',CURRENT_TIMESTAMP),
('templateadmin','SWA',0,@CityCodeID,'潮州','',CURRENT_TIMESTAMP),
('templateadmin','JIU',0,@CityCodeID,'九江','',CURRENT_TIMESTAMP),
('templateadmin','TCG',0,@CityCodeID,'塔城','',CURRENT_TIMESTAMP),
('templateadmin','MXZ',0,@CityCodeID,'梅州','',CURRENT_TIMESTAMP),
('templateadmin','NNY',0,@CityCodeID,'南阳','',CURRENT_TIMESTAMP),
('templateadmin','NLH',0,@CityCodeID,'宁蒗','',CURRENT_TIMESTAMP),
('templateadmin','CZX',0,@CityCodeID,'常州','',CURRENT_TIMESTAMP),
('templateadmin','KRL',0,@CityCodeID,'库尔勒','',CURRENT_TIMESTAMP),
('templateadmin','WUZ',0,@CityCodeID,'梧州','',CURRENT_TIMESTAMP),
('templateadmin','XUZ',0,@CityCodeID,'徐州','',CURRENT_TIMESTAMP),
('templateadmin','HLD',0,@CityCodeID,'海拉尔','',CURRENT_TIMESTAMP),
('templateadmin','YCU',0,@CityCodeID,'运城','',CURRENT_TIMESTAMP),
('templateadmin','LUM',0,@CityCodeID,'德宏','',CURRENT_TIMESTAMP),
('templateadmin','YUS',0,@CityCodeID,'玉树','',CURRENT_TIMESTAMP),
('templateadmin','WEF',0,@CityCodeID,'潍坊','',CURRENT_TIMESTAMP),
('templateadmin','HIA',0,@CityCodeID,'淮安','',CURRENT_TIMESTAMP),
('templateadmin','JHG',0,@CityCodeID,'西双版纳','',CURRENT_TIMESTAMP),
('templateadmin','URC',0,@CityCodeID,'乌鲁木齐','',CURRENT_TIMESTAMP),
('templateadmin','NZH',0,@CityCodeID,'满洲里','',CURRENT_TIMESTAMP),
('templateadmin','KJI',0,@CityCodeID,'喀纳斯','',CURRENT_TIMESTAMP),
('templateadmin','YNZ',0,@CityCodeID,'盐城','',CURRENT_TIMESTAMP),
('templateadmin','HRB',0,@CityCodeID,'哈尔滨','',CURRENT_TIMESTAMP),
('templateadmin','NGB',0,@CityCodeID,'宁波','',CURRENT_TIMESTAMP),
('templateadmin','SIA',0,@CityCodeID,'西安','',CURRENT_TIMESTAMP),
('templateadmin','THQ',0,@CityCodeID,'天水','',CURRENT_TIMESTAMP),
('templateadmin','RLK',0,@CityCodeID,'巴彦淖尔','',CURRENT_TIMESTAMP),
('templateadmin','HJJ',0,@CityCodeID,'怀化','',CURRENT_TIMESTAMP),
('templateadmin','ZQZ',0,@CityCodeID,'张家口','',CURRENT_TIMESTAMP),
('templateadmin','AAT',0,@CityCodeID,'阿勒泰','',CURRENT_TIMESTAMP),
('templateadmin','DLC',0,@CityCodeID,'大连','',CURRENT_TIMESTAMP),
('templateadmin','WUH',0,@CityCodeID,'武汉','',CURRENT_TIMESTAMP),
('templateadmin','NGQ',0,@CityCodeID,'阿里','',CURRENT_TIMESTAMP),
('templateadmin','WNH',0,@CityCodeID,'文山','',CURRENT_TIMESTAMP),
('templateadmin','LZY',0,@CityCodeID,'林芝','',CURRENT_TIMESTAMP),
('templateadmin','FUG',0,@CityCodeID,'阜阳','',CURRENT_TIMESTAMP),
('templateadmin','JIQ',0,@CityCodeID,'黔江','',CURRENT_TIMESTAMP),
('templateadmin','TSN',0,@CityCodeID,'天津市','',CURRENT_TIMESTAMP),
('templateadmin','LHK',0,@CityCodeID,'光化','',CURRENT_TIMESTAMP),
('templateadmin','GYU',0,@CityCodeID,'固原','',CURRENT_TIMESTAMP),
('templateadmin','MIG',0,@CityCodeID,'绵阳','',CURRENT_TIMESTAMP),
('templateadmin','OHE',0,@CityCodeID,'漠河','',CURRENT_TIMESTAMP),
('templateadmin','HCJ',0,@CityCodeID,'河池','',CURRENT_TIMESTAMP),
('templateadmin','BSD',0,@CityCodeID,'保山','',CURRENT_TIMESTAMP),
('templateadmin','YIW',0,@CityCodeID,'义乌','',CURRENT_TIMESTAMP),
('templateadmin','NDG',0,@CityCodeID,'齐齐哈尔','',CURRENT_TIMESTAMP),
('templateadmin','RHT',0,@CityCodeID,'阿拉善右旗','',CURRENT_TIMESTAMP),
('templateadmin','CAN',0,@CityCodeID,'广州','',CURRENT_TIMESTAMP),
('templateadmin','LYI',0,@CityCodeID,'临沂','',CURRENT_TIMESTAMP),
('templateadmin','JUZ',0,@CityCodeID,'衢州','',CURRENT_TIMESTAMP),
('templateadmin','TNA',0,@CityCodeID,'济南','',CURRENT_TIMESTAMP),
('templateadmin','YIN',0,@CityCodeID,'伊宁','',CURRENT_TIMESTAMP),
('templateadmin','YNJ',0,@CityCodeID,'延吉','',CURRENT_TIMESTAMP),
('templateadmin','LNJ',0,@CityCodeID,'临沧','',CURRENT_TIMESTAMP),
('templateadmin','CGQ',0,@CityCodeID,'长春','',CURRENT_TIMESTAMP),
('templateadmin','WNZ',0,@CityCodeID,'温州','',CURRENT_TIMESTAMP),
('templateadmin','GOQ',0,@CityCodeID,'格尔木','',CURRENT_TIMESTAMP),
('templateadmin','FUO',0,@CityCodeID,'佛山','',CURRENT_TIMESTAMP),
('templateadmin','XNN',0,@CityCodeID,'西宁','',CURRENT_TIMESTAMP),
('templateadmin','HSN',0,@CityCodeID,'舟山','',CURRENT_TIMESTAMP),
('templateadmin','LUM',0,@CityCodeID,'芒市','',CURRENT_TIMESTAMP),
('templateadmin','HUZ',0,@CityCodeID,'惠州','',CURRENT_TIMESTAMP),
('templateadmin','HMI',0,@CityCodeID,'哈密','',CURRENT_TIMESTAMP),
('templateadmin','FYJ',0,@CityCodeID,'抚远','',CURRENT_TIMESTAMP),
('templateadmin','DIG',0,@CityCodeID,'迪庆','',CURRENT_TIMESTAMP),
('templateadmin','DQA',0,@CityCodeID,'大庆','',CURRENT_TIMESTAMP),
('templateadmin','KMG',0,@CityCodeID,'昆明','',CURRENT_TIMESTAMP),
('templateadmin','LYA',0,@CityCodeID,'洛阳','',CURRENT_TIMESTAMP),
('templateadmin','CHG',0,@CityCodeID,'朝阳','',CURRENT_TIMESTAMP),
('templateadmin','HNY',0,@CityCodeID,'衡阳','',CURRENT_TIMESTAMP),
('templateadmin','JMU',0,@CityCodeID,'佳木斯','',CURRENT_TIMESTAMP),
('templateadmin','ERL',0,@CityCodeID,'二连浩特','',CURRENT_TIMESTAMP),
('templateadmin','TEN',0,@CityCodeID,'铜仁','',CURRENT_TIMESTAMP),
('templateadmin','TNH',0,@CityCodeID,'通化','',CURRENT_TIMESTAMP),
('templateadmin','ZYI',0,@CityCodeID,'遵义','',CURRENT_TIMESTAMP),
('templateadmin','AXF',0,@CityCodeID,'阿拉善左旗','',CURRENT_TIMESTAMP),
('templateadmin','TSN',0,@CityCodeID,'天津','',CURRENT_TIMESTAMP),
('templateadmin','ACX',0,@CityCodeID,'兴义','',CURRENT_TIMESTAMP),
('templateadmin','BHY',0,@CityCodeID,'北海','',CURRENT_TIMESTAMP),
('templateadmin','SHE',0,@CityCodeID,'沈阳','',CURRENT_TIMESTAMP),
('templateadmin','LHW',0,@CityCodeID,'兰州','',CURRENT_TIMESTAMP),
('templateadmin','SWA',0,@CityCodeID,'汕头','',CURRENT_TIMESTAMP),
('templateadmin','TLQ',0,@CityCodeID,'吐鲁番','',CURRENT_TIMESTAMP),
('templateadmin','SHP',0,@CityCodeID,'秦皇岛','',CURRENT_TIMESTAMP),
('templateadmin','XIL',0,@CityCodeID,'锡林浩特','',CURRENT_TIMESTAMP),
('templateadmin','YBP',0,@CityCodeID,'宜宾','',CURRENT_TIMESTAMP),
('templateadmin','WUX',0,@CityCodeID,'无锡','',CURRENT_TIMESTAMP),
('templateadmin','LCX',0,@CityCodeID,'龙岩','',CURRENT_TIMESTAMP),
('templateadmin','FOC',0,@CityCodeID,'福州','',CURRENT_TIMESTAMP),
('templateadmin','YTY',0,@CityCodeID,'泰州','',CURRENT_TIMESTAMP),
('templateadmin','JIC',0,@CityCodeID,'金昌','',CURRENT_TIMESTAMP),
('templateadmin','CTU',0,@CityCodeID,'成都','',CURRENT_TIMESTAMP),
('templateadmin','TYN',0,@CityCodeID,'太原','',CURRENT_TIMESTAMP),
('templateadmin','AEB',0,@CityCodeID,'百色','',CURRENT_TIMESTAMP),
('templateadmin','ENH',0,@CityCodeID,'恩施','',CURRENT_TIMESTAMP),
('templateadmin','WUT',0,@CityCodeID,'忻州','',CURRENT_TIMESTAMP),
('templateadmin','EJN',0,@CityCodeID,'额济纳旗','',CURRENT_TIMESTAMP),
('templateadmin','HGH',0,@CityCodeID,'杭州','',CURRENT_TIMESTAMP),
('templateadmin','DOY',0,@CityCodeID,'东营','',CURRENT_TIMESTAMP),
('templateadmin','DCY',0,@CityCodeID,'稻城','',CURRENT_TIMESTAMP),
('templateadmin','SHA',0,@CityCodeID,'上海市','',CURRENT_TIMESTAMP),
('templateadmin','YIE',0,@CityCodeID,'阿尔山','',CURRENT_TIMESTAMP),
('templateadmin','LXA',0,@CityCodeID,'拉萨','',CURRENT_TIMESTAMP),
('templateadmin','CIH',0,@CityCodeID,'长治','',CURRENT_TIMESTAMP),
('templateadmin','JXA',0,@CityCodeID,'鸡西','',CURRENT_TIMESTAMP),
('templateadmin','XIC',0,@CityCodeID,'西昌','',CURRENT_TIMESTAMP),
('templateadmin','KRY',0,@CityCodeID,'克拉玛依','',CURRENT_TIMESTAMP),
('templateadmin','DAT',0,@CityCodeID,'大同','',CURRENT_TIMESTAMP),
('templateadmin','GYS',0,@CityCodeID,'广元','',CURRENT_TIMESTAMP),
('templateadmin','FYN',0,@CityCodeID,'富蕴','',CURRENT_TIMESTAMP),
('templateadmin','BAV',0,@CityCodeID,'包头','',CURRENT_TIMESTAMP),
('templateadmin','SHS',0,@CityCodeID,'荆州','',CURRENT_TIMESTAMP),
('templateadmin','XMN',0,@CityCodeID,'厦门','',CURRENT_TIMESTAMP),
('templateadmin','KCA',0,@CityCodeID,'库车','',CURRENT_TIMESTAMP),
('templateadmin','ZUH',0,@CityCodeID,'珠海','',CURRENT_TIMESTAMP),
('templateadmin','JJN',0,@CityCodeID,'晋江','',CURRENT_TIMESTAMP),
('templateadmin','NTG',0,@CityCodeID,'南通','',CURRENT_TIMESTAMP),
('templateadmin','LLV',0,@CityCodeID,'吕梁','',CURRENT_TIMESTAMP),
('templateadmin','NNG',0,@CityCodeID,'南宁','',CURRENT_TIMESTAMP),
('templateadmin','TAO',0,@CityCodeID,'青岛','',CURRENT_TIMESTAMP),
('templateadmin','ZGN',0,@CityCodeID,'中山','',CURRENT_TIMESTAMP),
('templateadmin','DDG',0,@CityCodeID,'丹东','',CURRENT_TIMESTAMP),
('templateadmin','JGD',0,@CityCodeID,'加格达奇','',CURRENT_TIMESTAMP),
('templateadmin','JGN',0,@CityCodeID,'嘉峪关','',CURRENT_TIMESTAMP),
('templateadmin','LZO',0,@CityCodeID,'泸州','',CURRENT_TIMESTAMP),
('templateadmin','KHG',0,@CityCodeID,'喀什','',CURRENT_TIMESTAMP),
('templateadmin','PZI',0,@CityCodeID,'攀枝花','',CURRENT_TIMESTAMP),
('templateadmin','BFJ',0,@CityCodeID,'毕节','',CURRENT_TIMESTAMP),
('templateadmin','SJW',0,@CityCodeID,'石家庄','',CURRENT_TIMESTAMP),
('templateadmin','GHN',0,@CityCodeID,'广汉','',CURRENT_TIMESTAMP),
('templateadmin','WUS',0,@CityCodeID,'武夷山','',CURRENT_TIMESTAMP),
('templateadmin','HFE',0,@CityCodeID,'合肥','',CURRENT_TIMESTAMP),
('templateadmin','AHJ',0,@CityCodeID,'红原','',CURRENT_TIMESTAMP),
('templateadmin','HDG',0,@CityCodeID,'邯郸','',CURRENT_TIMESTAMP),
('templateadmin','CNI',0,@CityCodeID,'长海','',CURRENT_TIMESTAMP),
('templateadmin','DLU',0,@CityCodeID,'大理','',CURRENT_TIMESTAMP),
('templateadmin','CKG',0,@CityCodeID,'重庆','',CURRENT_TIMESTAMP),
('templateadmin','BJSPEK',0,@CityCodeID,'北京首都','',CURRENT_TIMESTAMP),
('templateadmin','IQM',0,@CityCodeID,'且末','',CURRENT_TIMESTAMP),
('templateadmin','KJH',0,@CityCodeID,'凯里','',CURRENT_TIMESTAMP),
('templateadmin','BJS',0,@CityCodeID,'北京','',CURRENT_TIMESTAMP),
('templateadmin','BPL',0,@CityCodeID,'博乐','',CURRENT_TIMESTAMP),
('templateadmin','SHA',0,@CityCodeID,'上海','',CURRENT_TIMESTAMP),
('templateadmin','AOG',0,@CityCodeID,'鞍山','',CURRENT_TIMESTAMP),
('templateadmin','ZHA',0,@CityCodeID,'湛江','',CURRENT_TIMESTAMP),
('templateadmin','MDG',0,@CityCodeID,'牡丹江','',CURRENT_TIMESTAMP),
('templateadmin','LLF',0,@CityCodeID,'永州','',CURRENT_TIMESTAMP),
('templateadmin','WUA',0,@CityCodeID,'乌海','',CURRENT_TIMESTAMP),
('templateadmin','HET',0,@CityCodeID,'呼和浩特','',CURRENT_TIMESTAMP),
('templateadmin','HPG',0,@CityCodeID,'神农架','',CURRENT_TIMESTAMP),
('templateadmin','YTY',0,@CityCodeID,'扬州','',CURRENT_TIMESTAMP),
('templateadmin','NLT',0,@CityCodeID,'那拉提','',CURRENT_TIMESTAMP),
('templateadmin','TCZ',0,@CityCodeID,'腾冲','',CURRENT_TIMESTAMP),
('templateadmin','BPX',0,@CityCodeID,'昌都','',CURRENT_TIMESTAMP),
('templateadmin','LJG',0,@CityCodeID,'丽江','',CURRENT_TIMESTAMP),
('templateadmin','HZH',0,@CityCodeID,'黎平','',CURRENT_TIMESTAMP),
('templateadmin','YZY',0,@CityCodeID,'张掖','',CURRENT_TIMESTAMP),
('templateadmin','INC',0,@CityCodeID,'银川','',CURRENT_TIMESTAMP),
('templateadmin','DSN',0,@CityCodeID,'鄂尔多斯','',CURRENT_TIMESTAMP),
('templateadmin','DNH',0,@CityCodeID,'敦煌','',CURRENT_TIMESTAMP),
('templateadmin','RKZ',0,@CityCodeID,'日喀则','',CURRENT_TIMESTAMP),
('templateadmin','LXI',0,@CityCodeID,'林西','',CURRENT_TIMESTAMP),
('templateadmin','CGD',0,@CityCodeID,'常德','',CURRENT_TIMESTAMP),
('templateadmin','IQN',0,@CityCodeID,'庆阳','',CURRENT_TIMESTAMP),
('templateadmin','LYG',0,@CityCodeID,'连云港','',CURRENT_TIMESTAMP),
('templateadmin','CIF',0,@CityCodeID,'赤峰','',CURRENT_TIMESTAMP),
('templateadmin','NKG',0,@CityCodeID,'南京','',CURRENT_TIMESTAMP),
('templateadmin','HLH',0,@CityCodeID,'乌兰浩特','',CURRENT_TIMESTAMP),
('templateadmin','KWL',0,@CityCodeID,'桂林','',CURRENT_TIMESTAMP),
('templateadmin','JGS',0,@CityCodeID,'井冈山','',CURRENT_TIMESTAMP),
('templateadmin','SIA',0,@CityCodeID,'咸阳','',CURRENT_TIMESTAMP),
('templateadmin','KGT',0,@CityCodeID,'康定','',CURRENT_TIMESTAMP),
('templateadmin','LZH',0,@CityCodeID,'柳州','',CURRENT_TIMESTAMP),
('templateadmin','DYG',0,@CityCodeID,'张家界','',CURRENT_TIMESTAMP),
('templateadmin','UYN',0,@CityCodeID,'榆林','',CURRENT_TIMESTAMP),
('templateadmin','CSX',0,@CityCodeID,'长沙','',CURRENT_TIMESTAMP),
('templateadmin','KHN',0,@CityCodeID,'南昌','',CURRENT_TIMESTAMP),
('templateadmin','AKU',0,@CityCodeID,'阿克苏','',CURRENT_TIMESTAMP),
('templateadmin','TXN',0,@CityCodeID,'黄山','',CURRENT_TIMESTAMP),
('templateadmin','YNT',0,@CityCodeID,'烟台','',CURRENT_TIMESTAMP),
('templateadmin','SWA',0,@CityCodeID,'揭阳','',CURRENT_TIMESTAMP),
('templateadmin','NAO',0,@CityCodeID,'南充','',CURRENT_TIMESTAMP),
('templateadmin','HAK',0,@CityCodeID,'海口','',CURRENT_TIMESTAMP),
('templateadmin','DAX',0,@CityCodeID,'达县','',CURRENT_TIMESTAMP),
('templateadmin','WEH',0,@CityCodeID,'威海','',CURRENT_TIMESTAMP),
('templateadmin','LPF',0,@CityCodeID,'六盘水','',CURRENT_TIMESTAMP),
('templateadmin','JJN',0,@CityCodeID,'泉州','',CURRENT_TIMESTAMP),
('templateadmin','AKA',0,@CityCodeID,'安康','',CURRENT_TIMESTAMP),
('templateadmin','GXH',0,@CityCodeID,'夏河','',CURRENT_TIMESTAMP),
('templateadmin','BJS',0,@CityCodeID,'北京市','',CURRENT_TIMESTAMP),
('templateadmin','TVS',0,@CityCodeID,'唐山','',CURRENT_TIMESTAMP),
('templateadmin','BJSNAY',0,@CityCodeID,'北京南苑','',CURRENT_TIMESTAMP),
('templateadmin','AQG',0,@CityCodeID,'安庆','',CURRENT_TIMESTAMP),
('templateadmin','WXN',0,@CityCodeID,'万州','',CURRENT_TIMESTAMP);